# Generated by Django 5.1.4 on 2025-01-09 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 9, 21, 41, 58, 13641), verbose_name='Tarih'),
        ),
    ]
